## Install Libraries

In [2]:
!pip install psycopg2-binary pandas google-cloud-bigquery

Collecting psycopg2-binary
  Obtaining dependency information for psycopg2-binary from https://files.pythonhosted.org/packages/c7/ae/8d8266f6dd183ab4d48b95b9674034e1b482a3f8619b33a0d86438694577/psycopg2_binary-2.9.11-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Downloading psycopg2_binary-2.9.11-cp311-cp311-macosx_10_9_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: pandas in /Users/afshansifat/anaconda3/lib/python3.11/site-packages (1.5.3)
Collecting google-cloud-bigquery
  Obtaining dependency information for google-cloud-bigquery from https://files.pythonhosted.org/packages/39/3c/c8cada9ec282b29232ed9aed5a0b5cca6cf5367cb2ffa8ad0d2583d743f1/google_cloud_bigquery-3.38.0-py3-none-any.whl.metadata
  Downloading google_cloud_bigquery-3.38.0-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/afshansifat/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/afshansifat/anaconda3/lib/python3.11/site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in /Users/afshansifat/anaconda3/lib/python3.11/site-packages (from pandas) (1.24.3)
Collecting google-api-core[grpc]<3.0.0,>=2.11.1 (from google-cloud-bigquery)
  Obtaining dependency information for google-api-core[grpc]<3.0.0,>=2.11.1 from https://files.pythonhosted.org/packages/ed/d4/90197b416cb61cefd316964fd9e7bd8324bcbafabf40eef14a9f20b81974/google_api_core-2.28.1-py3-none-any.whl.metadata
  Downloading google_api_core-2.28.1-py3-none-any.whl.metadata (3.3 kB)
Collecting google-auth<3.0.0,>=2.14.1 (from google-cloud-bigquery)
  Obtaining dependency information for google-auth<3.0.0,>=2.14.1 from https://files.pythonhosted.org/packages/6f/d1/385110a9ae86d91cc14c5282c61fe9f4dc41c0b9f7d423c6ad77038c4448/google_auth-2.43.0-py2.py3-none-any.whl.metadata
  Downloading google_auth-2.43.0-py2.py3-none-any.whl.metadata (6.6 kB)
Collecting google-cloud-core<3.0.0,>=2.4.1 (from google-cloud-bigquery)
  Obtaining dependency information for google-cloud-core<3.0.0,>=2.4.1 from https://files.pythonhosted.org/packages/89/20/bfa472e327c8edee00f04beecc80baeddd2ab33ee0e86fd7654da49d45e9/google_cloud_core-2.5.0-py3-none-any.whl.metadata
  Downloading google_cloud_core-2.5.0-py3-none-any.whl.metadata (3.1 kB)
Collecting google-resumable-media<3.0.0,>=2.0.0 (from google-cloud-bigquery)
  Obtaining dependency information for google-resumable-media<3.0.0,>=2.0.0 from https://files.pythonhosted.org/packages/82/35/b8d3baf8c46695858cb9d8835a53baa1eeb9906ddaf2f728a5f5b640fd1e/google_resumable_media-2.7.2-py2.py3-none-any.whl.metadata
  Downloading google_resumable_media-2.7.2-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting packaging>=24.2.0 (from google-cloud-bigquery)
  Obtaining dependency information for packaging>=24.2.0 from https://files.pythonhosted.org/packages/20/12/38679034af332785aac8774540895e234f4d07f7545804097de4b666afd8/packaging-25.0-py3-none-any.whl.metadata
  Downloading packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /Users/afshansifat/anaconda3/lib/python3.11/site-packages (from google-cloud-bigquery) (2.31.0)
Collecting googleapis-common-protos<2.0.0,>=1.56.2 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Obtaining dependency information for googleapis-common-protos<2.0.0,>=1.56.2 from https://files.pythonhosted.org/packages/c4/ab/09169d5a4612a5f92490806649ac8d41e3ec9129c636754575b3553f4ea4/googleapis_common_protos-1.72.0-py3-none-any.whl.metadata
  Downloading googleapis_common_protos-1.72.0-py3-none-any.whl.metadata (9.4 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Obtaining dependency information for protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 from https://files.pythonhosted.org/packages/e1/a9/b6eee662a6951b9c3640e8e452ab3e09f117d99fc10baa32d1581a0d4099/protobuf-6.33.0-cp39-abi3-macosx_10_9_universal2.whl.metadata
  Downloading protobuf-6.33.0-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Collecting proto-plus<2.0.0,>=1.22.3 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Obtaining dependency information for proto-plus<2.0.0,>=1.22.3 from https://files.pythonhosted.org/packages/4e/6d/280c4c2ce28b1593a19ad5239c8b826871fc6ec275c21afc8e1820108039/proto_plus-1.26.1-py3-none-any.whl.metadata
  Downloading proto_plus-1.26.1-py3-none-any.whl.metadata (2.2 kB)
Collecting grpcio<2.0.0,>=1.33.2 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Downloading grpcio-1.76.0.tar.gz (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 75.4 kB/s eta 0:00:0000:0100:05
  Preparing metadata (setup.py) ... done
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Obtaining dependency information for grpcio-status<2.0.0,>=1.33.2 from https://files.pythonhosted.org/packages/8c/cc/27ba60ad5a5f2067963e6a858743500df408eb5855e98be778eaef8c9b02/grpcio_status-1.76.0-py3-none-any.whl.metadata
  Downloading grpcio_status-1.76.0-py3-none-any.whl.metadata (1.1 kB)
Collecting cachetools<7.0,>=2.0.0 (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery)
  Obtaining dependency information for cachetools<7.0,>=2.0.0 from https://files.pythonhosted.org/packages/96/c5/1e741d26306c42e2bf6ab740b2202872727e0f606033c9dd713f8b93f5a8/cachetools-6.2.1-py3-none-any.whl.metadata
  Downloading cachetools-6.2.1-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/afshansifat/anaconda3/lib/python3.11/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.2.8)
Collecting rsa<5,>=3.1.4 (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery)
  Obtaining dependency information for rsa<5,>=3.1.4 from https://files.pythonhosted.org/packages/64/8d/0133e4eb4beed9e425d9a98ed6e081a55d195481b7632472be1af08d2f6b/rsa-4.9.1-py3-none-any.whl.metadata
  Downloading rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)
Collecting google-crc32c<2.0dev,>=1.0 (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery)
  Downloading google_crc32c-1.7.1.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: six>=1.5 in /Users/afshansifat/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/afshansifat/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/afshansifat/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/afshansifat/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/afshansifat/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2023.7.22)
Collecting typing-extensions~=4.12 (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery)
  Obtaining dependency information for typing-extensions~=4.12 from https://files.pythonhosted.org/packages/18/67/36e9267722cc04a6b9f15c7f3441c2363321a3ea07da7ae0c0707beb2a9c/typing_extensions-4.15.0-py3-none-any.whl.metadata
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/afshansifat/anaconda3/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.8)
Downloading psycopg2_binary-2.9.11-cp311-cp311-macosx_10_9_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 90.8 kB/s eta 0:00:0000:0100:02
Downloading google_cloud_bigquery-3.38.0-py3-none-any.whl (259 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.3/259.3 kB 73.6 kB/s eta 0:00:0000:0100:01
Downloading google_auth-2.43.0-py2.py3-none-any.whl (223 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 223.1/223.1 kB 103.4 kB/s eta 0:00:00a 0:00:01
Downloading google_cloud_core-2.5.0-py3-none-any.whl (29 kB)
Downloading google_resumable_media-2.7.2-py2.py3-none-any.whl (81 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.3/81.3 kB 51.2 kB/s eta 0:00:00a 0:00:01
Downloading packaging-25.0-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 61.0 kB/s eta 0:00:00a 0:00:01
Downloading cachetools-6.2.1-py3-none-any.whl (11 kB)
Downloading google_api_core-2.28.1-py3-none-any.whl (173 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.7/173.7 kB 46.9 kB/s eta 0:00:00a 0:00:01
Downloading googleapis_common_protos-1.72.0-py3-none-any.whl (297 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.5/297.5 kB 82.1 kB/s eta 0:00:0000:0100:01
Downloading grpcio_status-1.76.0-py3-none-any.whl (14 kB)
Downloading proto_plus-1.26.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 105.1 kB/s eta 0:00:00a 0:00:01
Downloading protobuf-6.33.0-cp39-abi3-macosx_10_9_universal2.whl (427 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 427.5/427.5 kB 80.6 kB/s eta 0:00:0000:0100:01
Downloading rsa-4.9.1-py3-none-any.whl (34 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 186.0 kB/s eta 0:00:00a 0:00:01
Building wheels for collected packages: google-crc32c, grpcio
  Building wheel for google-crc32c (pyproject.toml) ... done
  Created wheel for google-crc32c: filename=google_crc32c-1.7.1-py3-none-any.whl size=13241 sha256=6f165e62292a29f9870bb534bd4b5278b89ce37875a3985cc378724b9f9afc64
  Stored in directory: /Users/afshansifat/Library/Caches/pip/wheels/0d/cf/f8/409157786b7ea3bd654c62612d6f42bd62c780c75386f5dd6d
  Building wheel for grpcio (setup.py) ... done
  Created wheel for grpcio: filename=grpcio-1.76.0-cp311-cp311-macosx_11_0_x86_64.whl size=5739346 sha256=7753e37dfe946c18975263cffe320c0edcfbec01d281e63786f4be79ad6ef5cb
  Stored in directory: /Users/afshansifat/Library/Caches/pip/wheels/26/9c/5e/8a7d04471639962953fc774e062de0b6b6f479863051788a39
Successfully built google-crc32c grpcio
Installing collected packages: typing-extensions, rsa, psycopg2-binary, protobuf, packaging, google-crc32c, cachetools, proto-plus, grpcio, googleapis-common-protos, google-resumable-media, google-auth, grpcio-status, google-api-core, google-cloud-core, google-cloud-bigquery
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
  Attempting uninstall: packaging
    Found existing installation: packaging 23.0
    Uninstalling packaging-23.0:
      Successfully uninstalled packaging-23.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tables 3.8.0 requires blosc2~=2.0.0, which is not installed.
tables 3.8.0 requires cython>=0.29.21, which is not installed.
spyder 5.4.3 requires pyqt5<5.16, which is not installed.
spyder 5.4.3 requires pyqtwebengine<5.16, which is not installed.
python-lsp-black 1.2.1 requires black>=22.3.0, but you have black 0.0 which is incompatible.
Successfully installed cachetools-6.2.1 google-api-core-2.28.1 google-auth-2.43.0 google-cloud-bigquery-3.38.0 google-cloud-core-2.5.0 google-crc32c-1.7.1 google-resumable-media-2.7.2 googleapis-common-protos-1.72.0 grpcio-1.76.0 grpcio-status-1.76.0 packaging-25.0 proto-plus-1.26.1 protobuf-6.33.0 psycopg2-binary-2.9.11 rsa-4.9.1 typing-extensions-4.15.0

## Import libraries

In [15]:
import pandas as pd              # Data manipulation with DataFrames
from sqlalchemy import create_engine, text  # DB connection and executing SQL
import datetime                  # Work with dates and times
from google.cloud import bigquery  # Interact with BigQuery
from google.oauth2 import service_account  # Authenticate with Google Cloud
import warnings
warnings.filterwarnings('ignore')  # Suppress warning messages

## Set the connection parameters

In [20]:
# Connection parameters
db_user = "postgres"         # your PostgreSQL username
db_password = "database123"             # Please enter your PostgreSQL password
db_host = "localhost"        # host (use '127.0.0.1' if localhost doesn't work)
db_port = "5432"             # default PostgreSQL port
db_name = "DW Assignment 02"     # your database name

# Create the connection string
connection_string = f"postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"

# Create engine
engine = create_engine(connection_string)

In [21]:
engine

Engine(postgresql://postgres:***@localhost:5432/DW Assignment 02)

## Test connection

In [22]:
try:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT version();"))
        for row in result:
            print("Connected to:", row[0])
except Exception as e:
    print("Connection failed:", e)

Connected to: PostgreSQL 17.4 on x86_64-apple-darwin23.6.0, compiled by Apple clang version 15.0.0 (clang-1500.3.9.4), 64-bit

## Get data from Postgres

In [23]:
query = text("SELECT * FROM student_lifestyle_dataset;")
# query = text("SELECT * FROM student_stress_survey;")

query

In [24]:
# Fetch data into pandas DataFrame
university_a = pd.read_sql(query, engine)

In [25]:
# Show the data
university_a.head()

,student_id,study_hours_per_day,extracurricular_hours_per_day,sleep_hours_per_day,social_hours_per_day,physical_activity_hours_per_day,gpa,stress_level
0,1,2.5,1.0,7.5,2.0,0.5,3.1,Moderate
1,2,3.0,0.5,6.0,1.5,1.0,3.5,Low
2,3,1.5,2.5,5.5,3.0,0.5,2.8,High
3,4,4.0,1.5,7.0,2.5,1.0,3.9,Low
4,5,2.0,1.0,6.5,2.0,0.8,3.2,Moderate

In [26]:
university_a.columns

Index(['student_id', 'study_hours_per_day', 'extracurricular_hours_per_day',
       'sleep_hours_per_day', 'social_hours_per_day',
       'physical_activity_hours_per_day', 'gpa', 'stress_level'],
      dtype='object')

## Import data from Google Forms/Sheet

In [29]:
# url = "https://docs.google.com/spreadsheets/d/1XDSepScHjT0jigBgePY49sycmD_F3S8Nb3vvQCo1A9E/export?format=csv"
# url = "https://docs.google.com/spreadsheets/d/1SdJ8yg7jl0TuLulPFuoaiHyHpAI72OhMnsZ_s3ucGmI/edit?usp=sharing"


university_b = pd.read_csv("University_B.csv")

In [30]:

university_b.head()

,Student_ID,Study_Hours_Per_Day,Extracurricular_Hours_Per_Day,Sleep_Hours_Per_Day,Social_Hours_Per_Day,Physical_Activity_Hours_Per_Day,GPA,Stress_Level
0,1,6.9,3.8,8.7,2.8,1.8,2.99,Moderate
1,2,5.3,3.5,8.0,4.2,3.0,2.75,Low
2,3,5.1,3.9,9.2,1.2,4.6,2.67,Low
3,4,6.5,2.1,7.2,1.7,6.5,2.88,Moderate
4,5,8.1,0.6,6.5,2.2,6.6,3.51,High

In [31]:
university_b.columns

Index(['Student_ID', 'Study_Hours_Per_Day', 'Extracurricular_Hours_Per_Day',
       'Sleep_Hours_Per_Day', 'Social_Hours_Per_Day',
       'Physical_Activity_Hours_Per_Day', 'GPA', 'Stress_Level'],
      dtype='object')

In [32]:
university_a.columns

Index(['student_id', 'study_hours_per_day', 'extracurricular_hours_per_day',
       'sleep_hours_per_day', 'social_hours_per_day',
       'physical_activity_hours_per_day', 'gpa', 'stress_level'],
      dtype='object')

In [33]:
university_a["university"] = "A"
university_b["university"] = "B"

In [34]:
print("University A Data:")
print(university_a.head())

print("\nUniversity B Data:")
print(university_b.head())

University A Data:
   student_id  study_hours_per_day  extracurricular_hours_per_day  \
0           1                  2.5                            1.0
1           2                  3.0                            0.5
2           3                  1.5                            2.5
3           4                  4.0                            1.5
4           5                  2.0                            1.0

   sleep_hours_per_day  social_hours_per_day  physical_activity_hours_per_day  \
0                  7.5                   2.0                              0.5
1                  6.0                   1.5                              1.0
2                  5.5                   3.0                              0.5
3                  7.0                   2.5                              1.0
4                  6.5                   2.0                              0.8

   gpa stress_level university
0  3.1     Moderate          A
1  3.5          Low          A
2  2.8         High          A
3  3.9          Low          A
4  3.2     Moderate          A

University B Data:
   Student_ID  Study_Hours_Per_Day  Extracurricular_Hours_Per_Day  \
0           1                  6.9                            3.8
1           2                  5.3                            3.5
2           3                  5.1                            3.9
3           4                  6.5                            2.1
4           5                  8.1                            0.6

   Sleep_Hours_Per_Day  Social_Hours_Per_Day  Physical_Activity_Hours_Per_Day  \
0                  8.7                   2.8                              1.8
1                  8.0                   4.2                              3.0
2                  9.2                   1.2                              4.6
3                  7.2                   1.7                              6.5
4                  6.5                   2.2                              6.6

    GPA Stress_Level university
0  2.99     Moderate          B
1  2.75          Low          B
2  2.67          Low          B
3  2.88     Moderate          B
4  3.51         High          B

## STANDARDIZE COLUMN 
1. Make sure both sources have same column names.
2. Remove extra characters from column name.
3. Change the case to lower for consistency.
4. Make sure that same columns exist in both sources.

In [38]:
university_b.columns[8]

'university'

In [39]:
university_a.columns[8]

'university'

In [43]:
# Rename Google Sheet columns to match PostgreSQL schema

rename_map = {}

for i in range(len(university_b.columns)):
    rename_map[university_b.columns[i]] = university_a.columns[i]
    
# key : value
# dictionary[key] = value

In [17]:
rename_map

{'Timestamp': 'timestamp',
 'Email Address': 'email_address',
 'Full Name': 'full_name',
 'Gender': 'gender',
 'Date of Birth': 'date_of_birth',
 'Where do you originally belong to (city)?': 'hometown',
 'Department / Program': 'department',
 'Semester': 'semester',
 'How many hours do you study on average per day?': 'study_hours_per_day',
 'How often do you have multiple deadlines or exams in the same week?': 'multiple_deadlines',
 'How confident do you feel managing your academic workload?': 'workload_confidence',
 'How many hours do you sleep per night (on average)?': 'sleep_hours',
 'How often do you exercise or play sports per week?': 'exercise_frequency',
 'Do you often skip meals due to workload or stress?': 'skip_meals',
 'How much time do you spend on social media daily?': 'social_media_hours',
 'How often do you feel anxious or overwhelmed?': 'feel_anxious',
 'How often do you have trouble concentrating?': 'trouble_concentrating',
 'Rate your overall stress level this semester:': 'stress_level',
 'What do you usually do to manage stress?': 'stress_management',
 'Do you think your university provides enough mental health support?': 'mental_health_support',
 'How often do you dedicate time to hobbies or non-academic activities per week?': 'hobbies_time',
 'Which social media app do you feel negatively impacts your mood or increases stress levels?': 'stressful_social_media',
 'Any thoughts or suggestions about stress management?': 'stress_suggestions'}

In [44]:
university_b.rename(columns=rename_map, inplace=True)

In [46]:
university_b.columns

Index(['student_id', 'study_hours_per_day', 'extracurricular_hours_per_day',
       'sleep_hours_per_day', 'social_hours_per_day',
       'physical_activity_hours_per_day', 'gpa', 'stress_level', 'university'],
      dtype='object')

In [47]:
# Convert column names to lowercase for consistency
university_b.columns = university_b.columns.str.lower()
university_a.columns = university_a.columns.str.lower()

In [48]:

university_a.columns = university_a.columns.str.strip().str.replace(' ', '_').str.lower()
university_b.columns = university_b.columns.str.strip().str.replace(' ', '_').str.lower()

In [49]:
set(university_a.columns)

{'extracurricular_hours_per_day',
 'gpa',
 'physical_activity_hours_per_day',
 'sleep_hours_per_day',
 'social_hours_per_day',
 'stress_level',
 'student_id',
 'study_hours_per_day',
 'university'}

In [50]:
# Ensure same columns exist in both DataFrames
missing_cols = set(university_a.columns) - set(university_b.columns)

missing_cols


# for col in missing_cols:
#     gs_data[col] = None #any operation or just make it null or drop it

set()

## COMBINE DATA

In [51]:
university_a.shape

(10, 9)

In [52]:
university_b.shape

(2000, 9)

In [53]:
# Append both datasets
df_combined = pd.concat([university_a, university_b], ignore_index=True)

In [54]:
df_combined.shape

(2010, 9)

In [55]:
df_combined.columns

Index(['student_id', 'study_hours_per_day', 'extracurricular_hours_per_day',
       'sleep_hours_per_day', 'social_hours_per_day',
       'physical_activity_hours_per_day', 'gpa', 'stress_level', 'university'],
      dtype='object')

# DATA CLEANING / TRANSFORMATION

### Missing values

In [57]:
df_combined.isnull().sum().sum()

0

In [61]:
df_combined.isnull().sum()

student_id                         0
study_hours_per_day                0
extracurricular_hours_per_day      0
sleep_hours_per_day                0
social_hours_per_day               0
physical_activity_hours_per_day    0
gpa                                0
stress_level                       0
university                         0
dtype: int64

**If there is any missing value, deal with it**

### Data Types

In [65]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2010 entries, 0 to 2009
Data columns (total 9 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   student_id                       2010 non-null   int64
 1   study_hours_per_day              2010 non-null   float64
 2   extracurricular_hours_per_day    2010 non-null   float64
 3   sleep_hours_per_day              2010 non-null   float64
 4   social_hours_per_day             2010 non-null   float64
 5   physical_activity_hours_per_day  2010 non-null   float64
 6   gpa                              2010 non-null   float64
 7   stress_level                     2010 non-null   object
 8   university                       2010 non-null   object
dtypes: float64(6), int64(1), object(2)
memory usage: 141.5+ KB

In [37]:
# date column => it has values like "", Null, "text"

In [70]:
df_combined["stress_level"] = df_combined["stress_level"].astype("category")
df_combined["university"] = df_combined["university"].astype("category")

In [72]:
df_combined.duplicated().sum()

0

In [74]:
df_combined["student_id"].is_unique

False

In [76]:
df_combined["student_id"].duplicated().sum()

10

In [78]:
df_combined[df_combined["student_id"].duplicated(keep=False)].sort_values("student_id")

,student_id,study_hours_per_day,extracurricular_hours_per_day,sleep_hours_per_day,social_hours_per_day,physical_activity_hours_per_day,gpa,stress_level,university
0,1,2.5,1.0,7.5,2.0,0.5,3.10,Moderate,A
10,1,6.9,3.8,8.7,2.8,1.8,2.99,Moderate,B
1,2,3.0,0.5,6.0,1.5,1.0,3.50,Low,A
11,2,5.3,3.5,8.0,4.2,3.0,2.75,Low,B
2,3,1.5,2.5,5.5,3.0,0.5,2.80,High,A
12,3,5.1,3.9,9.2,1.2,4.6,2.67,Low,B
3,4,4.0,1.5,7.0,2.5,1.0,3.90,Low,A
13,4,6.5,2.1,7.2,1.7,6.5,2.88,Moderate,B
4,5,2.0,1.0,6.5,2.0,0.8,3.20,Moderate,A
14,5,8.1,0.6,6.5,2.2,6.6,3.51,High,B
5,6,3.5,0.5,5.5,1.5,0.5,3.00,High,A
15,6,6.0,2.1,8.0,0.3,7.6,2.85,Moderate,B
6,7,4.5,1.0,8.0,2.0,1.5,3.85,Low,A
16,7,8.0,0.7,5.3,5.7,4.3,3.08,High,B
17,8,8.4,1.8,5.6,3.0,5.2,3.20,High,B
7,8,2.5,1.5,6.0,3.0,1.0,3.40,Moderate,A
18,9,5.2,3.6,6.3,4.0,4.9,2.82,Low,B
8,9,1.0,0.5,5.0,1.0,0.3,2.60,High,A
9,10,3.0,2.0,7.5,2.5,1.2,3.70,Low,A
19,10,7.7,0.7,9.8,4.5,1.3,2.76,Moderate,B

In [80]:
df_combined = df_combined.reset_index(drop=True)
df_combined["record_id"] = df_combined.index + 1


# Now record_id is unique for each row, while student_id stays as a grouping variable.

In [83]:
df_combined["record_id"].duplicated().sum()

0

**If there is any column with numeric values but of object datatype, then convert it in a given way**

In [41]:
# for col in df_combined.select_dtypes(exclude="datetime64[ns]").columns:
#     # Check if any value in column can be converted to numeric
#     if pd.to_numeric(df_combined[col], errors='coerce').notna().any():
#         # Convert column to numeric (float), coercing errors
#         df_combined[col] = pd.to_numeric(df_combined[col], errors='coerce')

In [84]:
df_combined.dtypes

student_id                            int64
study_hours_per_day                 float64
extracurricular_hours_per_day       float64
sleep_hours_per_day                 float64
social_hours_per_day                float64
physical_activity_hours_per_day     float64
gpa                                 float64
stress_level                       category
university                         category
record_id                             int64
dtype: object

### Text inconsistency

In [85]:
df_combined.select_dtypes(include="object").columns

Index([], dtype='object')

In [87]:
for col in df_combined.select_dtypes(include="object").columns:
    df_combined[col] = df_combined[col].str.title()
    df_combined[col] = df_combined[col].str.strip() # trim

In [91]:
# Reorder columns so that record_id comes first
cols = ['record_id'] + [col for col in df_combined.columns if col != 'record_id']
df_combined = df_combined[cols]

In [92]:
df_combined.head()

,record_id,student_id,study_hours_per_day,extracurricular_hours_per_day,sleep_hours_per_day,social_hours_per_day,physical_activity_hours_per_day,gpa,stress_level,university
0,1,1,2.5,1.0,7.5,2.0,0.5,3.1,Moderate,A
1,2,2,3.0,0.5,6.0,1.5,1.0,3.5,Low,A
2,3,3,1.5,2.5,5.5,3.0,0.5,2.8,High,A
3,4,4,4.0,1.5,7.0,2.5,1.0,3.9,Low,A
4,5,5,2.0,1.0,6.5,2.0,0.8,3.2,Moderate,A

### Duplicates

In [93]:
df_combined.duplicated().sum()

0

In [ ]:
# data exported to pgAdmin

In [97]:
df_combined.to_sql('students_table', con=engine, index=False, if_exists='replace')
print(" Data exported successfully to PostgreSQL!")

 Data exported successfully to PostgreSQL!