## Install Libraries

In [1]:
#!pip install psycopg2-binary pandas google-cloud-bigquery

## Import libraries

In [122]:
import pandas as pd              # Data manipulation with DataFrames
from sqlalchemy import create_engine, text  # DB connection and executing SQL
import datetime                  # Work with dates and times
from google.cloud import bigquery  # Interact with BigQuery
from google.oauth2 import service_account  # Authenticate with Google Cloud
import warnings
warnings.filterwarnings('ignore')  # Suppress warning messages
# !pip install python-dotenv

## Set the connection parameters

In [74]:
secrets = {}

with open("logs.txt") as f:
    for line in f:
        line = line.strip()
        if line and "=" in line:
            key, value = line.split("=", 1)
            secrets[key.strip()] = value.strip()

db_user = secrets.get("DB_USER")   #  PostgreSQL username 
db_password = secrets.get("DB_PASSWORD")    # PostgreSQL password 
db_host = secrets.get("DB_HOST")     # host (use '127.0.0.1' if localhost doesn't work) 
db_port = secrets.get("DB_PORT")     # default PostgreSQL port 
db_name = secrets.get("DB_NAME")    # database name

# Create the connection string
connection_string = f"postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"

# Create engine
engine = create_engine(connection_string)

In [75]:
engine

Engine(postgresql://postgres:***@localhost:5432/DW Assignment 02)

## Test connection

In [76]:
try:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT version();"))
        for row in result:
            print("Connected to:", row[0])
except Exception as e:
    print("Connection failed:", e)

Connected to: PostgreSQL 17.4 on x86_64-apple-darwin23.6.0, compiled by Apple clang version 15.0.0 (clang-1500.3.9.4), 64-bit

## Get data from Postgres

In [77]:
query = text("SELECT * FROM student_lifestyle_dataset;")
query

In [78]:
# Fetch data into pandas DataFrame
university_a = pd.read_sql(query, engine)

In [79]:
# Show the data
university_a.head()

,student_id,study_hours_per_day,extracurricular_hours_per_day,sleep_hours_per_day,social_hours_per_day,physical_activity_hours_per_day,gpa,stress_level
0,1,2.5,1.0,7.5,2.0,0.5,3.1,Moderate
1,2,3.0,0.5,6.0,1.5,1.0,3.5,Low
2,3,1.5,2.5,5.5,3.0,0.5,2.8,High
3,4,4.0,1.5,7.0,2.5,1.0,3.9,Low
4,5,2.0,1.0,6.5,2.0,0.8,3.2,Moderate

In [80]:
university_a.columns

Index(['student_id', 'study_hours_per_day', 'extracurricular_hours_per_day',
       'sleep_hours_per_day', 'social_hours_per_day',
       'physical_activity_hours_per_day', 'gpa', 'stress_level'],
      dtype='object')

## Import data from Google Forms/Sheet

In [81]:

university_b = pd.read_csv("University_B.csv")

In [82]:

university_b.head()

,Student_ID,Study_Hours_Per_Day,Extracurricular_Hours_Per_Day,Sleep_Hours_Per_Day,Social_Hours_Per_Day,Physical_Activity_Hours_Per_Day,GPA,Stress_Level
0,1,6.9,3.8,8.7,2.8,1.8,2.99,Moderate
1,2,5.3,3.5,8.0,4.2,3.0,2.75,Low
2,3,5.1,3.9,9.2,1.2,4.6,2.67,Low
3,4,6.5,2.1,7.2,1.7,6.5,2.88,Moderate
4,5,8.1,0.6,6.5,2.2,6.6,3.51,High

In [83]:
university_b.columns

Index(['Student_ID', 'Study_Hours_Per_Day', 'Extracurricular_Hours_Per_Day',
       'Sleep_Hours_Per_Day', 'Social_Hours_Per_Day',
       'Physical_Activity_Hours_Per_Day', 'GPA', 'Stress_Level'],
      dtype='object')

In [84]:
university_a.columns

Index(['student_id', 'study_hours_per_day', 'extracurricular_hours_per_day',
       'sleep_hours_per_day', 'social_hours_per_day',
       'physical_activity_hours_per_day', 'gpa', 'stress_level'],
      dtype='object')

In [85]:
university_a["university"] = "A"
university_b["university"] = "B"

In [86]:
print("University A Data:")
print(university_a.head())

print("\nUniversity B Data:")
print(university_b.head())

University A Data:
   student_id  study_hours_per_day  extracurricular_hours_per_day  \
0           1                  2.5                            1.0
1           2                  3.0                            0.5
2           3                  1.5                            2.5
3           4                  4.0                            1.5
4           5                  2.0                            1.0

   sleep_hours_per_day  social_hours_per_day  physical_activity_hours_per_day  \
0                  7.5                   2.0                              0.5
1                  6.0                   1.5                              1.0
2                  5.5                   3.0                              0.5
3                  7.0                   2.5                              1.0
4                  6.5                   2.0                              0.8

   gpa stress_level university
0  3.1     Moderate          A
1  3.5          Low          A
2  2.8         High          A
3  3.9          Low          A
4  3.2     Moderate          A

University B Data:
   Student_ID  Study_Hours_Per_Day  Extracurricular_Hours_Per_Day  \
0           1                  6.9                            3.8
1           2                  5.3                            3.5
2           3                  5.1                            3.9
3           4                  6.5                            2.1
4           5                  8.1                            0.6

   Sleep_Hours_Per_Day  Social_Hours_Per_Day  Physical_Activity_Hours_Per_Day  \
0                  8.7                   2.8                              1.8
1                  8.0                   4.2                              3.0
2                  9.2                   1.2                              4.6
3                  7.2                   1.7                              6.5
4                  6.5                   2.2                              6.6

    GPA Stress_Level university
0  2.99     Moderate          B
1  2.75          Low          B
2  2.67          Low          B
3  2.88     Moderate          B
4  3.51         High          B

## STANDARDIZE COLUMN 
1. Make sure both sources have same column names.
2. Remove extra characters from column name.
3. Change the case to lower for consistency.
4. Make sure that same columns exist in both sources.

In [87]:
university_b.columns[8]

'university'

In [88]:
university_a.columns[8]

'university'

In [89]:
# Rename Google Sheet columns to match PostgreSQL schema

rename_map = {}

for i in range(len(university_b.columns)):
    rename_map[university_b.columns[i]] = university_a.columns[i]
    
# key : value
# dictionary[key] = value

In [90]:
rename_map

{'Student_ID': 'student_id',
 'Study_Hours_Per_Day': 'study_hours_per_day',
 'Extracurricular_Hours_Per_Day': 'extracurricular_hours_per_day',
 'Sleep_Hours_Per_Day': 'sleep_hours_per_day',
 'Social_Hours_Per_Day': 'social_hours_per_day',
 'Physical_Activity_Hours_Per_Day': 'physical_activity_hours_per_day',
 'GPA': 'gpa',
 'Stress_Level': 'stress_level',
 'university': 'university'}

In [91]:
university_b.rename(columns=rename_map, inplace=True)

In [92]:
university_b.columns

Index(['student_id', 'study_hours_per_day', 'extracurricular_hours_per_day',
       'sleep_hours_per_day', 'social_hours_per_day',
       'physical_activity_hours_per_day', 'gpa', 'stress_level', 'university'],
      dtype='object')

In [93]:
# Convert column names to lowercase for consistency
university_b.columns = university_b.columns.str.lower()
university_a.columns = university_a.columns.str.lower()

In [94]:

university_a.columns = university_a.columns.str.strip().str.replace(' ', '_').str.lower()
university_b.columns = university_b.columns.str.strip().str.replace(' ', '_').str.lower()

In [95]:
set(university_a.columns)

{'extracurricular_hours_per_day',
 'gpa',
 'physical_activity_hours_per_day',
 'sleep_hours_per_day',
 'social_hours_per_day',
 'stress_level',
 'student_id',
 'study_hours_per_day',
 'university'}

In [96]:
# Ensure same columns exist in both DataFrames
missing_cols = set(university_a.columns) - set(university_b.columns)

missing_cols


# for col in missing_cols:
#     gs_data[col] = None #any operation or just make it null or drop it

set()

## COMBINE DATA

In [97]:
university_a.shape

(10, 9)

In [98]:
university_b.shape

(2000, 9)

In [99]:
# Append both datasets
df_combined = pd.concat([university_a, university_b], ignore_index=True)

In [100]:
df_combined.shape

(2010, 9)

In [101]:
df_combined.columns

Index(['student_id', 'study_hours_per_day', 'extracurricular_hours_per_day',
       'sleep_hours_per_day', 'social_hours_per_day',
       'physical_activity_hours_per_day', 'gpa', 'stress_level', 'university'],
      dtype='object')

# DATA CLEANING / TRANSFORMATION

### Missing values

In [102]:
df_combined.isnull().sum().sum()

0

In [103]:
df_combined.isnull().sum()

student_id                         0
study_hours_per_day                0
extracurricular_hours_per_day      0
sleep_hours_per_day                0
social_hours_per_day               0
physical_activity_hours_per_day    0
gpa                                0
stress_level                       0
university                         0
dtype: int64

**If there is any missing value, deal with it**

### Data Types

In [104]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2010 entries, 0 to 2009
Data columns (total 9 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   student_id                       2010 non-null   int64
 1   study_hours_per_day              2010 non-null   float64
 2   extracurricular_hours_per_day    2010 non-null   float64
 3   sleep_hours_per_day              2010 non-null   float64
 4   social_hours_per_day             2010 non-null   float64
 5   physical_activity_hours_per_day  2010 non-null   float64
 6   gpa                              2010 non-null   float64
 7   stress_level                     2010 non-null   object
 8   university                       2010 non-null   object
dtypes: float64(6), int64(1), object(2)
memory usage: 141.5+ KB

In [105]:
# date column => it has values like "", Null, "text"

In [106]:
df_combined["stress_level"] = df_combined["stress_level"].astype("category")
df_combined["university"] = df_combined["university"].astype("category")

In [107]:
df_combined.duplicated().sum()

0

In [108]:
df_combined["student_id"].is_unique

False

In [109]:
df_combined["student_id"].duplicated().sum()

10

In [110]:
df_combined[df_combined["student_id"].duplicated(keep=False)].sort_values("student_id")

,student_id,study_hours_per_day,extracurricular_hours_per_day,sleep_hours_per_day,social_hours_per_day,physical_activity_hours_per_day,gpa,stress_level,university
0,1,2.5,1.0,7.5,2.0,0.5,3.10,Moderate,A
10,1,6.9,3.8,8.7,2.8,1.8,2.99,Moderate,B
1,2,3.0,0.5,6.0,1.5,1.0,3.50,Low,A
11,2,5.3,3.5,8.0,4.2,3.0,2.75,Low,B
2,3,1.5,2.5,5.5,3.0,0.5,2.80,High,A
12,3,5.1,3.9,9.2,1.2,4.6,2.67,Low,B
3,4,4.0,1.5,7.0,2.5,1.0,3.90,Low,A
13,4,6.5,2.1,7.2,1.7,6.5,2.88,Moderate,B
4,5,2.0,1.0,6.5,2.0,0.8,3.20,Moderate,A
14,5,8.1,0.6,6.5,2.2,6.6,3.51,High,B
5,6,3.5,0.5,5.5,1.5,0.5,3.00,High,A
15,6,6.0,2.1,8.0,0.3,7.6,2.85,Moderate,B
6,7,4.5,1.0,8.0,2.0,1.5,3.85,Low,A
16,7,8.0,0.7,5.3,5.7,4.3,3.08,High,B
17,8,8.4,1.8,5.6,3.0,5.2,3.20,High,B
7,8,2.5,1.5,6.0,3.0,1.0,3.40,Moderate,A
18,9,5.2,3.6,6.3,4.0,4.9,2.82,Low,B
8,9,1.0,0.5,5.0,1.0,0.3,2.60,High,A
9,10,3.0,2.0,7.5,2.5,1.2,3.70,Low,A
19,10,7.7,0.7,9.8,4.5,1.3,2.76,Moderate,B

In [111]:
df_combined = df_combined.reset_index(drop=True)
df_combined["record_id"] = df_combined.index + 1


# Now record_id is unique for each row, while student_id stays as a grouping variable.

In [112]:
df_combined["record_id"].duplicated().sum()

0

**If there is any column with numeric values but of object datatype, then convert it in a given way**

In [113]:
# for col in df_combined.select_dtypes(exclude="datetime64[ns]").columns:
#     # Check if any value in column can be converted to numeric
#     if pd.to_numeric(df_combined[col], errors='coerce').notna().any():
#         # Convert column to numeric (float), coercing errors
#         df_combined[col] = pd.to_numeric(df_combined[col], errors='coerce')

In [114]:
df_combined.dtypes

student_id                            int64
study_hours_per_day                 float64
extracurricular_hours_per_day       float64
sleep_hours_per_day                 float64
social_hours_per_day                float64
physical_activity_hours_per_day     float64
gpa                                 float64
stress_level                       category
university                         category
record_id                             int64
dtype: object

### Text inconsistency

In [115]:
df_combined.select_dtypes(include="object").columns

Index([], dtype='object')

In [116]:
for col in df_combined.select_dtypes(include="object").columns:
    df_combined[col] = df_combined[col].str.title()
    df_combined[col] = df_combined[col].str.strip() # trim

In [117]:
# Reorder columns so that record_id comes first
cols = ['record_id'] + [col for col in df_combined.columns if col != 'record_id']
df_combined = df_combined[cols]

In [118]:
df_combined.head()

,record_id,student_id,study_hours_per_day,extracurricular_hours_per_day,sleep_hours_per_day,social_hours_per_day,physical_activity_hours_per_day,gpa,stress_level,university
0,1,1,2.5,1.0,7.5,2.0,0.5,3.1,Moderate,A
1,2,2,3.0,0.5,6.0,1.5,1.0,3.5,Low,A
2,3,3,1.5,2.5,5.5,3.0,0.5,2.8,High,A
3,4,4,4.0,1.5,7.0,2.5,1.0,3.9,Low,A
4,5,5,2.0,1.0,6.5,2.0,0.8,3.2,Moderate,A

### Duplicates

In [119]:
df_combined.duplicated().sum()

0

# Connect with BigQuery

In [120]:
cred = secrets.get("BIGQUERY_KEY")
credentials = service_account.Credentials.from_service_account_file(cred)
client = bigquery.Client(credentials=credentials, project=credentials.project_id)

print("Connected to BigQuery project:", client.project)

Connected to BigQuery project: data-warehouse-475007

## LOAD TO BIGQUERY

For Loading data to BigQuery, you can use any of the function
1. **client.load_table_from_dataframe()**
   * Uses the official BigQuery Python client
   * It's Faster, supports large datasets, and gives more control over BigQuery jobs.
     
3. **to_gbq()** 
    * A pandas-friendly wrapper
    * Simpler for small-to-medium DataFrames, integrates directly with pandas, but less control and slower for very large datasets.

In [121]:
# Define destination table
table_id = f"{client.project}.ETL_DataWarehouse.A_stress_data"

# Load data to BigQuery
job = client.load_table_from_dataframe(df_combined, table_id)
job.result()  # wait until the job completes

print("Data successfully loaded to BigQuery:", table_id)

Data successfully loaded to BigQuery: data-warehouse-475007.ETL_DataWarehouse.A_stress_data

In [55]:
# !pip install pandas-gbq --upgrade

In [62]:
# from pandas_gbq import to_gbq
# from google.oauth2 import service_account

# # Set credentials
# credentials = service_account.Credentials.from_service_account_file(cred)

# # Push DataFrame to BigQuery
# to_gbq(
#     df_combined,
#     destination_table='survey.A_stress_data',
#     project_id=credentials.project_id,
#     if_exists='replace',  # options: 'fail', 'replace', 'append'
#     credentials=credentials
# )